[config.custom_colors]

# Blended to match palette
red            = "#FF0000"
green          = "#00FF00"
yellow         = "#FFFF00"
blue           = "#0000FF"
magenta        = "#FF00FF"
cyan           = "#00FFFF"
white          = "#FFFFFF"
purple         = "#800080"
orange         = "#FF8000"

[templates.quickshell]
input_path = 'templates/quickshell'
output_path = '~/.config/quickshell/components/Material.qml'

[templates.kitty]
input_path = 'templates/kitty'
output_path = '~/Hyprland-Dots/.config/kitty/Material.conf'

[templates.neovim]
input_path = 'templates/neovim'
output_path = '~/.cache/wal/colors-wal.vim'

[templates.gtk]
input_path = 'templates/gtk'
output_path = '~/Hyprland-Dots/theme_srcs/gtk/src/sass/_color-palette-material.scss'

[templates.kvantum_kvconfig]
input_path = 'templates/kvantum.kvconfig'
output_path = '~/.config/Kvantum/Material/Material.kvconfig'

[templates.kvantum_svg]
input_path = 'templates/kvantum.svg'
output_path = '~/.config/Kvantum/Material/Material.svg'

[templates.bibata]
input_path = 'templates/bibata'
output_path = '~/Hyprland-Dots/theme_srcs/cursors/schemes/Bibata-Modern-Material.json'

[templates.script_vars]
input_path = 'templates/script_vars'
output_path = '~/material_colours'

