exec-once = quickshell --daemonize

exec-once = wl-paste --type text --watch cliphist store # Stores clipboard text

exec-once = wl-paste --type image --watch cliphist store # Stores clipboard images

exec-once = cliphist wipe # Clear clipboard for new session

exec-once = hypridle # Start idle daemon

exec-once = ~/DelayedStartup.sh

