#!/bin/sh

if [ "$#" -gt 1 ]; then
	echo "Invalid number of arguments."
	exit 1
fi

if [ ! -e "$1" ] && [ ! -d "$1" ]; then
  echo "File or directory does not exsist at: $1"
  exit 1
fi

if [ "$#" -eq 0 ]; then
	path=$(pwd)
else
	path=$(realpath $1)
fi

wl-copy $path

echo 'Copied to clipboard:'
echo $path

exit 0

