#!/bin/bash

noMatugen=0
lightCurs=0
noNotify=0

for arg in "$@"; do
  case "$arg" in
    --nomatugen)
      noMatugen=1
      ;;
    --lightCurs)
      lightCurs=1
      ;;
    --noNotify)
      noNotify=1
      ;;
  esac
done

if [[ ! "$noMatugen" == 1 ]]; then
  matugen image "$(quickshell ipc call config get desktop wallpaper)" > /dev/null 2>&1 || exit 1
fi

LOCKFILE="$HOME/.cache/themegen.lck"
PENDING='1'

# If the lockfile exists, we check if another job is already pending
# If there is no pending job then we make one
# If there is no lockfile, we create one

# This system prevents two jobs from running at once.
# If the script is run 1 or more times while a job is running
# that job will complete then one new job will be started.

if [[ -e "$LOCKFILE" ]]; then
  if [[ ! $(cat "$LOCKFILE") == "$PENDING" ]]; then
    echo "$PENDING" > "$LOCKFILE"
    inotifywait "$LOCKFILE" -e delete > /dev/null 2>&1
  else
    exit 0
  fi
fi

if [[ ! -e "$LOCKFILE" ]]; then
  touch "$LOCKFILE"
fi

if [[ ! "$noNotify" -eq 1 ]]; then
  notify-send -a 'Material Theme Generation' 'Starting generation' 'Generating material GTK, icon, and cursor themes.'
fi

"$HOME"/Hyprland-Dots/theme_srcs/install-gtk.sh material --script > /dev/null 2>&1
"$HOME"/Hyprland-Dots/theme_srcs/install-icons.sh material --script > /dev/null 2>&1

if [[ "$lightCurs" -eq 1 ]]; then
  curs='material-light'
else
  curs='material'
fi
"$HOME/Hyprland-Dots/theme_srcs/install-cursors.sh" "$curs" --script --regenerate > /dev/null 2>&1

rm "$LOCKFILE"

if [[ ! "$noNotify" -eq 1 ]]; then
  notify-send -a 'Material Theme Generation' 'Generation complete' 'GTK, icon, and cursor theme generation has finished.'
fi

