#!/bin/bash

time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$(xdg-user-dir PICTURES)/Screenshots"
file="Screenshot_${time}_${RANDOM}.png"

# countdown
countdown() {
	notifIDCountdown=$(notify-send -h string:x-canonical-private-synchronous:shot-notify -t 1500 -i clock -p "Taking shot in : $sec")
	for sec in $(seq $1 -1 1); do
		notify-send -h string:x-canonical-private-synchronous:shot-notify -t 1500 -i clock "Taking shot in : $sec" -r $notifIDCountdown
		sleep 1
	done
}

# take shots
shotnow() {
	cd ${dir} && grim - | tee "$file" | wl-copy
}

shot5() {
	countdown '5'
	sleep 1 && cd ${dir} && grim - | tee "$file" | wl-copy
}

shot10() {
	countdown '10'
	sleep 1 && cd ${dir} && grim - | tee "$file" | wl-copy
}

shotwin() {
	w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
	w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
	cd ${dir} && grim -g "$w_pos $w_size" - | tee "$file" | wl-copy
}

shotarea() {
	cd ${dir} && grim -g "$(slurp -b 9399b230 -c bac2deff -s 00000000 -w 2)" - | tee "$file" | wl-copy
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

if [[ "$1" == "--now" ]]; then
	shotnow
elif [[ "$1" == "--in5" ]]; then
	shot5
elif [[ "$1" == "--in10" ]]; then
	shot10
elif [[ "$1" == "--win" ]]; then
	shotwin
elif [[ "$1" == "--area" ]]; then
	shotarea
else
	echo -e "Available Options : --now --in5 --in10 --win --area"
  exit 1
fi

if [[ -s "$dir/$file" ]]; then
  notify-send -h string:x-canonical-private-synchronous:shot-notify -i camera -t 5000 -u low "Screenshot Saved." -p
else
  rm ${dir}/${file}
fi

exit 0

