#!/bin/bash

# ==== Adding a theme ==== #

# Define theme variables
# Add wallpaper
# Add quickshell theme
# Add gtk and kvantum themes
# Add icon and cursor themes
# Add kitty theme
# Add neovim theme
# Add macchina theme & messages


# ==== Common ==== #

function help() {
  echo 'Syntax: SetTheme <option> <flags>'
  echo 'Options:'
  echo '1. Everforest'
  echo '2. Catppuccin Mocha'
  echo '3. Rose Pine'
  echo ''
  echo 'Flags:'
  echo '--noconfirm'
  exit "$1"
}

noconfirm=0

selected=$(echo "$1" | tr '[:upper:]' '[:lower:]')

shift
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --noconfirm)
      noconfirm=1
      ;;
    -h | --help)
      help 0
      ;;
    -w | --wallpaper)
      shift
      if [[ -z "$1" ]]; then
        help 1
      fi
      customWall="$1"
      ;;
    *)
      help 1
      ;;
  esac
  shift
done

prompt() {
  # Syntax: prompt-text default

  local prompt default input output
  prompt=$1
  default=$(echo "$2" | tr '[:upper:]' '[:lower:]')

  if [[ "$noconfirm" -eq 1 ]]; then
    echo "$default"
  else
    read -rp "$prompt" input
    input=$(echo "$input" | tr '[:upper:]' '[:lower:]')

    if [[ $input == 'y' || ( -z $input && $default == 'y' ) ]]; then
      output=1
    elif [[ $input == 'n' || ( -z $input && $default == 'n' ) ]]; then
      output=0
    else
      if [[ $default == 'y' ]]; then output=1; else output=0; fi
    fi
    echo "$output"
  fi
}

if [[ ! "$selected" == 'material' && ! "$customWall" ]]; then
  changeWall=$(prompt 'Change wallpaper? (y/N) ' 'n')
fi
lightCurs=$(prompt 'Enable light cursors? (y/N) ' 'n')

if [[ "$selected" -eq 1 || "$selected" == "everforest" ]]; then
  theme='Everforest'
  gtk='Colloid-Green-Everforest'
  quickshell='everforest'
  icons='Colloid-Green-Everforest-Dark'
  cursors='Bibata-Modern-Everforest'
  cursorsLight='Bibata-Modern-Everforest-Light'
  accent='A7C080'
  border='3C4841'
  wall="$HOME/Hyprland-Dots/Wallpapers/Everforest/Accent.png"
elif [[ "$selected" -eq 2 || "$selected" == "catmocha" ]]; then
  theme='CatMocha'
  gtk='Colloid-Purple-Catppuccin'
  quickshell='catMocha'
  icons='Colloid-Purple-Catppuccin-Dark'
  cursors='Bibata-Modern-CatMocha'
  cursorsLight='Bibata-Modern-CatLatte'
  accent='B4BEFE'
  border='5A5F7F'  # 50% dimmed accent
  wall="$HOME/Hyprland-Dots/Wallpapers/Catppuccin/Accent.png"
elif [[ "$selected" -eq 3 || "$selected" == "rosepine" ]]; then
  theme='Rose-Pine'
  gtk='Colloid-Teal-Rosepine'
  quickshell='rosePine'
  icons='Colloid-Teal-Rosepine-Dark'
  cursors='Bibata-Modern-Rose-Pine'
  cursorsLight='Bibata-Modern-Rose-Pine-Dawn'
  accent='9CCFD8'
  border='4E686C'  # 50% dimmed accent
  wall="$HOME/Hyprland-Dots/Wallpapers/Rose-Pine/Accent.png"
elif [[ "$selected" -eq 3 || "$selected" == "material" ]]; then
  if [[ -n "$customWall" ]]; then
    wall="$customWall"
  else
    wall="$(quickshell ipc call config get desktop wallpaper)"
  fi

  matugen image "$wall" > /dev/null 2>&1 || exit 1

  pid=$$
  {
    parent_pid="$pid"

    args=(--noMatugen --noNotify)
    if [[ "$lightCurs" -eq 1 ]]; then args+=(--lightCurs); fi
    "$HOME"/Scripts/GenerateMaterial "${args[@]}"

    if ! kill -0 "$parent_pid" > /dev/null 2>&1; then
      notify-send -a 'Set Theme' 'Generation complete' 'GTK, icon, and cursor theme generation has finished.'
    fi
  } &

  generation_pid=$!

  . "$HOME/material_colours"

  theme='Material'
  gtk='Colloid-Material'
  quickshell='material'
  icons='Colloid-Material-Dark'
  cursors='Bibata-Modern-Material'
  cursorsLight='Bibata-Modern-Material-Light'
  accent="${material_d_primary:1}"
  border="${material_d_outline_var:1}"
else
  help 1
fi


# === Quickshell === #
echo 'Setting Quickshell theme...'
if [[ $(quickshell list --all) == "No running instances." ]]; then
  echo "No instances of Quickshell found, launching..."
  quickshell --daemonize > /dev/null 2>&1
fi
quickshell ipc call config colours "$quickshell" > /dev/null 2>&1
if [[ "$changeWall" -eq 1 ]]; then
  quickshell ipc call config wallpaper "$wall" > /dev/null 2>&1
fi


# ==== GTK theme + icons ==== #
if [[ "$lightCurs" -eq 1 ]]; then
  cursors="$cursorsLight"
fi

echo 'Setting GTK theme, icons & cursors...'
if [[ -e $HOME/.config/gtk-3.0/settings.ini ]]; then
  sed -i "s/.*gtk-theme-name.*/gtk-theme-name=$gtk/" "$HOME"/.config/gtk-3.0/settings.ini
  sed -i "s/.*gtk-icon-theme-name.*/gtk-icon-theme-name=$icons/" "$HOME"/.config/gtk-3.0/settings.ini
  sed -i "s/.*gtk-cursor-theme-name.*/gtk-cursor-theme-name=$cursors/" "$HOME"/.config/gtk-3.0/settings.ini
fi
if [[ -e $HOME/.config/gtk-4.0/settings.ini ]]; then
  sed -i "s/.*gtk-theme-name.*/gtk-theme-name=$gtk/" "$HOME"/.config/gtk-4.0/settings.ini
  sed -i "s/.*gtk-icon-theme-name.*/gtk-icon-theme-name=$icons/" "$HOME"/.config/gtk-4.0/settings.ini
  sed -i "s/.*gtk-cursor-theme-name.*/gtk-cursor-theme-name=$cursors/" "$HOME"/.config/gtk-4.0/settings.ini
fi

if [[ ! -d $HOME/.icons ]]; then
  mkdir $HOME/.icons
fi

echo '[Icon Theme]'       > "$HOME/.icons/default/index.theme"
echo 'Name=Default'      >> "$HOME/.icons/default/index.theme"
echo "Inherits=$cursors" >> "$HOME/.icons/default/index.theme"
echo ''                  >> "$HOME/.icons/default/index.theme"

hyprctl setcursor $cursors 32 > /dev/null 2>&1
gsettings set org.gnome.desktop.interface cursor-theme "$cursors"
gsettings set org.gnome.desktop.interface gtk-theme "$gtk"
gsettings set org.gnome.desktop.interface icon-theme "$icons"

# Libadwaita
if [[ -e "$HOME/.config/gtk-4.0/gtk.css" || -L "$HOME/.config/gtk-4.0/gtk.css" ]]; then
  rm -f "$HOME/.config/gtk-4.0/gtk.css"
fi
if [[ -e "$HOME/.config/gtk-4.0/gtk-dark.css" || -L "$HOME/.config/gtk-4.0/gtk-dark.css" ]]; then
  rm -f "$HOME/.config/gtk-4.0/gtk-dark.css"
fi
if [[ -e "$HOME/.config/gtk-4.0/assets" || -L "$HOME/.config/gtk-4.0/assets" ]]; then
  rm -rf "$HOME/.config/gtk-4.0/assets"  # -r is in case it's not a symlink already (is a directory)
fi

ln -s "$HOME/.themes/$theme/gtk-4.0/gtk-dark.css" "$HOME/.config/gtk-4.0"
ln -s "$HOME/.themes/$theme/gtk-4.0/gtk.css"      "$HOME/.config/gtk-4.0"
ln -s "$HOME/.themes/$theme/gtk-4.0/assets"       "$HOME/.config/gtk-4.0"


# ==== Kvantum ==== #
echo 'Setting Kvantum theme...'
echo '[General]'     > "$HOME/.config/Kvantum/kvantum.kvconfig"
echo "theme=$theme" >> "$HOME/.config/Kvantum/kvantum.kvconfig"


# ==== Qt icons ==== #
echo 'Setting QT icon theme...'
sed -i "s/.*icon_theme.*/icon_theme=$icons/" "$HOME/.config/qt5ct/qt5ct.conf"
sed -i "s/.*icon_theme.*/icon_theme=$icons/" "$HOME/.config/qt6ct/qt6ct.conf"


# ==== Kitty ==== #
echo 'Setting Kitty theme...'
(
  cd "$HOME"/.config/kitty || exit 1
  if [[ -e ./Colours.conf || -L ./Colours.conf ]]; then
    rm ./Colours.conf
  fi
  ln -s ./"$theme".conf ./Colours.conf
)


# ==== Macchina ==== #
# echo 'Setting Macchina theme...'
# sed -i "s/.*key_color.*/key_color = \"#$accent\"/" $HOME/.config/macchina/themes/Theme.toml
# sed -i "s/.*separator_color.*/separator_color = \"#$accent\"/" $HOME/.config/macchina/themes/Theme.toml
# sed -i "s/.*msgFile=.*/msgFile=~\/Scripts\/Messages\/$theme/" $HOME/Scripts/RandomMessage
# The above replace the entire line that contains the first string with the second string


# ==== Cava ====
echo 'Setting Cava theme...'
sed -i "s/.*foreground.*/foreground = '#$accent'/" ~/.config/cava/config


# ==== Neovim ==== #
if [[ -d $HOME/.config/nvim/lua/plugins ]]; then
  cd "$HOME"/.config/nvim/lua/plugins || exit 1
  if [[ -e ./Theme.lua ]]; then
    rm ./Theme.lua
  fi
  ln -s ./$theme ./Theme.lua
else
  echo 'lazy.nvim not found, please set Neovim theme manually.'
fi


# ==== Hyprland ==== #
echo 'Setting Hyprland theme...'

cat > "$HOME"/.config/hypr/hyprland/theming.conf <<EOL
# This file is auto-generated by the SetTheme script
# Do not place your own changes in here as they will be overwritten

general {
    col.active_border = 0xff${accent}
    col.inactive_border = 0xff${border}
}

EOL


# ==== Finish up ==== #
echo 'Reloading Kitty...'
killall -SIGUSR1 kitty > /dev/null 2>&1  # Output gets deleted

echo 'Reloading Quickshell...'
sleep 0.1  # Gives Quickshell some time to set wallpaper properly
quickshell ipc call config reload

echo 'Reloading Cava...'
killall -SIGUSR1 cava > /dev/null 2>&1

echo 'Reloading Hyprland...'
hyprctl reload > /dev/null 2>&1

if [[ -n "$generation_pid" ]] && kill -0 "$generation_pid" > /dev/null 2>&1; then
  notify-send -a 'Set Theme' 'Background tasks running' 'Theme has been applied, but either gtk, icon, or cursor themes are still generating.'
else
  notify-send -a 'Set Theme' 'Done!' 'Theme has been applied.'
fi

echo 'Done!'

