format = """
[░▒▓](#89b4fa)\
[  ](bg:#89b4fa fg:#1e1e2e)\
[](bg:#b4befe fg:#89b4fa)\
$directory\
[](fg:#b4befe bg:#313244)\
$git_branch\
$git_status\
[](fg:#313244)\
\n$character
"""

right_format = """
[](fg:#313244)\
$status\
[](fg:#6c7086 bg:#313244)\
$time\
[▓▒░](#6c7086)
"""

[directory]
style = "fg:#1e1e2e bg:#b4befe"
format = "[ $path ]($style)"
truncation_length = 6
truncation_symbol = "…/"
read_only = ""

[git_branch]
symbol = ""
style = "bg:#313244"
format = '[[ $symbol $branch ](fg:#cdd6f4 bg:#313244)]($style)'

[git_status]
style = "bg:#313244"
format = '[[($all_status$ahead_behind )](fg:#cdd6f4 bg:#313244)]($style)'

[status]
style = "fg:#f38ba8 bg:#313244"
symbol = " "
sigint_symbol = " "
not_executable_symbol = " "
not_found_symbol = " "
signal_symbol = " "
format = '[ $symbol$status ]($style)'
disabled = false

[time]
style = "bg:#6c7086 fg:#cdd6f4"
format = "[  $time ]($style)"
disabled = false

